name: test-matrix

on:
  workflow_dispatch:

jobs:
  job-matrix:
    strategy:
      matrix:
        TARGET_LAMBDA_FUNCTION_NAMES: [testlambda, test2lambda, test3lambda]
    runs-on: ubuntu-latest

    steps:
    - run: | 
       echo "===== Target ${{ matrix.TARGET_LAMBDA_FUNCTION_NAMES }} ====="
       echo "aws lambda list-versions-by-function --function-name ${{ matrix.TARGET_LAMBDA_FUNCTION_NAMES }} --query 'Versions[-1].Version' --output text"
       touch ${FILENAME}
       VARIABLE=$(ls -l ${FILENAME})
       echo "${VARIABLE}[OK]"
      env:
       FILENAME: text.txt