version: '3'

services:
    amplify:
        build: ./
        ports:
            - "8080:3000"
            - "20002:20002"
        volumes:
            - ./amplifyapp/:/var/www/app
            - ~/.aws/:/root/.aws/
        tty: true
#        command: "npm run serve"
        command: "npm start"