name: "Lambda Test"
on:
   pull_request:
    branches:
     - main

    types: [opened, synchronize, reopened, closed]
   workflow_dispatch:
#-------------------------#
# 環境変数
#-------------------------#
env:
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    SLACK_USERNAME: GitHubActions
    SLACK_CHANNEL: test_mbs
    SLACK_ICON: https://octodex.github.com/images/Robotocat.png
 
permissions:
    id-token: write
    contents: read
    pull-requests: write


jobs:
  terraform:
    name: "AWS Lambda Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ap-northeast-1

      - name: List S3 buckets
        run: aws s3 ls

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
  
      - name: Run Lambda tests
        run: |
          python -m unittest discover -s tests