name: test-matrix

on:
  workflow_dispatch:

#-------------------------#
# 環境変数
#-------------------------#
env:
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    SLACK_USERNAME: GitHubActions
    SLACK_CHANNEL: test_mbs
    SLACK_ICON: https://octodex.github.com/images/Robotocat.png

jobs:

  job-test:
    runs-on: ubuntu-latest
    steps:
    - name: setup tfcmt
      env:
        TFCMT_VERSION: v4.10.0
      run: |
        wget "https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz" -O /tmp/tfcmt.tar.gz
        tar xzf /tmp/tfcmt.tar.gz -C /tmp
        mv /tmp/tfcmt /usr/local/bin
        tfcmt --version


  job-matrix:
    needs: job-test  # Add this line to specify the dependency
    strategy:
      matrix:
        TARGET_LAMBDA_FUNCTION_NAMES: [testlambda, test2lambda, test3lambda]
    runs-on: ubuntu-latest

    steps:
    - name: Update Lambda prd Alias 
      run: | 
       echo "===== Target ${{ matrix.TARGET_LAMBDA_FUNCTION_NAMES }} ====="
       echo "aws lambda list-versions-by-function --function-name ${{ matrix.TARGET_LAMBDA_FUNCTION_NAMES }} --query 'Versions[-1].Version' --output text"
       touch ${FILENAME}
       VARIABLE=$(ls -l ${FILENAME})
       echo "${VARIABLE}[OK]"
      env:
       FILENAME: text.txt

  notifications:
    needs: [job-test, job-matrix]
    runs-on: ubuntu-latest
    steps:
      #-- Slack通知 --#
      # 成功

    - name: Slack Notification on Success
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: Deploy Success
        SLACK_COLOR: good
          # 失敗
    - name: Slack Notification on Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: Deploy Failure
        SLACK_COLOR: danger